# fork_dict1
dict1 = {'Start': (-100, 100),
         'W': 3.5,
         'R': 10,
         'StartLaneID': 1,
         'StartBoundaryID': 1,
         'LaneNumber': 4,
         'BoundaryNumber': 7,
         'LaneAssetType': {'Boundary1': 'SW',
                           'Boundary2': 'SW',
                           'Boundary3': 'SW',
                           'Boundary4': 'DW',
                           'Boundary5': 'SW',
                           'Boundary6': 'SW',
                           'Boundary7': 'SW',
                           },  # boundary的个数根据组件类型得出
         'Function': '+',
         'Type': 'fork',
         'K': '+',
         'Flag': '单车道右弯曲并入单向双车道'}
# fork_dict2
dict2 = {'Start': (-60, 100),
         'W': 3.5,
         'R': 10,
         'StartLaneID': 1,
         'StartBoundaryID': 1,
         'LaneNumber': 4,
         'BoundaryNumber': 7,
         'LaneAssetType': {'Boundary1': 'SW',
                           'Boundary2': 'SW',
                           'Boundary3': 'SW',
                           'Boundary4': 'SY',
                           'Boundary5': 'SW',
                           'Boundary6': 'SW',
                           'Boundary7': 'SW',
                           },  # boundary的个数根据组件类型得出
         'Function': '+',
         'K': '+',
         'Type': 'fork',
         'Flag': '单车道右弯曲并入双向双车道'}
# fork_dict3
dict3 = {'Start': (-20, 100),
         'W': 3.5,
         'R': 10,
         'StartLaneID': 1,
         'StartBoundaryID': 1,
         'LaneNumber': 6,
         'BoundaryNumber': 9,
         'LaneAssetType': {'Boundary1': 'SW',
                           'Boundary2': 'SW',
                           'Boundary3': 'SW',
                           'Boundary4': 'DW',
                           'Boundary5': 'SY',
                           'Boundary6': 'SW',
                           'Boundary7': 'SW',
                           'Boundary8': 'SY',
                           'Boundary9': 'SW',
                           },  # boundary的个数根据组件类型得出
         'Function': '+',
         'K': '+',
         'Type': 'fork',
         'Flag': '单车道右弯曲并入二前行三车道'}
# fork_dict4
dict4 = {'Start': (20, 100),
         'W': 3.5,
         'R': 10,
         'StartLaneID': 1,
         'StartBoundaryID': 1,
         'LaneNumber': 6,
         'BoundaryNumber': 9,
         'LaneAssetType': {'Boundary1': 'SW',
                           'Boundary2': 'SW',
                           'Boundary3': 'SW',
                           'Boundary4': 'SY',
                           'Boundary5': 'DW',
                           'Boundary6': 'SW',
                           'Boundary7': 'SW',
                           'Boundary8': 'DW',
                           'Boundary9': 'SW',
                           },  # boundary的个数根据组件类型得出
         'Function': '+',
         'K': '+',
         'Type': 'fork',
         'Flag': '单车道右弯曲并入一前行三车道'}
# fork_dict5
dict5 = {'Start': (60, 100),
         'W': 3.5,
         'R': 10,
         'StartLaneID': 1,
         'StartBoundaryID': 1,
         'LaneNumber': 8,
         'BoundaryNumber': 11,
         'LaneAssetType': {'Boundary1': 'SW',
                           'Boundary2': 'SW',
                           'Boundary3': 'SW',
                           'Boundary4': 'DW',
                           'Boundary5': 'SDY',
                           'Boundary6': 'DW',
                           'Boundary7': 'SW',
                           'Boundary8': 'SW',
                           'Boundary9': 'SY',
                           'Boundary10': 'DW',
                           'Boundary11': 'SW',

                           },  # boundary的个数根据组件类型得出
         'Function': '+',
         'K': '+',
         'Type': 'fork',
         'Flag': '单车道右弯曲并入四车道'}
# fork_dict6
dict6 = {'Start': (100, 100),
         'W': 3.5,
         'R': 10,
         'StartLaneID': 1,
         'StartBoundaryID': 1,
         'LaneNumber': 4,
         'BoundaryNumber': 7,
         'LaneAssetType': {'Boundary1': 'SW',
                           'Boundary2': 'SW',
                           'Boundary3': 'SW',
                           'Boundary4': 'DW',
                           'Boundary5': 'SW',
                           'Boundary6': 'SW',
                           'Boundary7': 'SW',
                           },  # boundary的个数根据组件类型得出
         'Function': '+',
         'K': '+',
         'Type': 'fork',
         'Flag': '单车道左弯曲并入单向双车道'}
# fork_dict7
dict7 = {'Start': (-100, 0),
         'W': 3.5,
         'R': 10,
         'StartLaneID': 1,
         'StartBoundaryID': 1,
         'LaneNumber': 6,
         'BoundaryNumber': 9,
         'LaneAssetType': {'Boundary1': 'SW',
                           'Boundary2': 'DW',
                           'Boundary3': 'SW',
                           'Boundary4': 'SW',
                           'Boundary5': 'DW',
                           'Boundary6': 'SY',
                           'Boundary7': 'SW',
                           'Boundary8': 'SW',
                           'Boundary9': 'SW',
                           },  # boundary的个数根据组件类型得出
         'Function': '+',
         'K': '+',
         'Type': 'fork',
         'Flag': '单向双车道右弯曲并入二前行三车道'}
# fork_dict8
dict8 = {'Start': (-60, 0),
         'W': 3.5,
         'R': 10,
         'StartLaneID': 1,
         'StartBoundaryID': 1,
         'LaneNumber': 6,
         'BoundaryNumber': 9,
         'LaneAssetType': {'Boundary1': 'SW',
                           'Boundary2': 'SY',
                           'Boundary3': 'SW',
                           'Boundary4': 'SW',
                           'Boundary5': 'SY',
                           'Boundary6': 'DW',
                           'Boundary7': 'SW',
                           'Boundary8': 'SW',
                           'Boundary9': 'SW',
                           },  # boundary的个数根据组件类型得出
         'Function': '+',
         'K': '+',
         'Type': 'fork',
         'Flag': '双向双车道右弯曲并入一前行三车道'}
# fork_dict9
dict9 = {'Start': (-20, 0),
         'W': 3.5,
         'R': 10,
         'StartLaneID': 1,
         'StartBoundaryID': 1,
         'LaneNumber': 8,
         'BoundaryNumber': 11,
         'LaneAssetType': {'Boundary1': 'SW',
                           'Boundary2': 'DW',
                           'Boundary3': 'SW',
                           'Boundary4': 'SW',
                           'Boundary5': 'DW',
                           'Boundary6': 'SDY',
                           'Boundary7': 'DW',
                           'Boundary8': 'SW',
                           'Boundary9': 'SW',
                           'Boundary10': 'DW',
                           'Boundary11': 'SW',
                           },  # boundary的个数根据组件类型得出
         'Function': '+',
         'K': '+',
         'Type': 'fork',
         'Flag': '单向双车道右弯曲并入四车道'}

# fork_dict10
dict10 = {'Start': (20, 0),
          'W': 3.5,
          'R': 10,
          'StartLaneID': 1,
          'StartBoundaryID': 1,
          'LaneNumber': 6,
          'BoundaryNumber': 9,
          'LaneAssetType': {'Boundary1': 'SW',
                            'Boundary2': 'SY',
                            'Boundary3': 'SW',
                            'Boundary4': 'SW',
                            'Boundary5': 'SY',
                            'Boundary6': 'DW',
                            'Boundary7': 'SW',
                            'Boundary8': 'SW',
                            'Boundary9': 'SW',
                            },  # boundary的个数根据组件类型得出
          'Function': '+',
          'K': '+',
          'Type': 'fork',
          'Flag': '双向双车道左弯曲并入二前行三车道'}
# fork_dict11
dict11 = {'Start': (60, 0),
          'W': 3.5,
          'R': 10,
          'StartLaneID': 1,
          'StartBoundaryID': 1,
          'LaneNumber': 8,
          'BoundaryNumber': 11,
          'LaneAssetType': {'Boundary1': 'SW',
                            'Boundary2': 'SY',
                            'Boundary3': 'DW',
                            'Boundary4': 'SW',
                            'Boundary5': 'SW',
                            'Boundary6': 'DW',
                            'Boundary7': 'SDY',
                            'Boundary8': 'DW',
                            'Boundary9': 'SW',
                            'Boundary10': 'SW',
                            'Boundary11': 'SW',
                            },  # boundary的个数根据组件类型得出
          'Function': '+',
          'K': '+',
          'Type': 'fork',
          'Flag': '二前行三车道右弯曲并入四车道'}
# fork_dict12
dict12 = {'Start': (100, 0),
          'W': 3.5,
          'R': 10,
          'StartLaneID': 1,
          'StartBoundaryID': 1,
          'LaneNumber': 8,
          'BoundaryNumber': 11,
          'LaneAssetType': {'Boundary1': 'SW',
                            'Boundary2': 'DW',
                            'Boundary3': 'SW',
                            'Boundary4': 'SW',
                            'Boundary5': 'DW',
                            'Boundary6': 'SDY',
                            'Boundary7': 'DW',
                            'Boundary8': 'SW',
                            'Boundary9': 'SW',
                            'Boundary10': 'DW',
                            'Boundary11': 'SW',
                            },  # boundary的个数根据组件类型得出
          'Function': '+',
          'K': '+',
          'Type': 'fork',
          'Flag': '一前行三车道左弯曲并入四车道'}
# fork_dict13
dict13 = {'Start': (-100, -100),
          'W': 3.5,
          'R': 10,
          'StartLaneID': 1,
          'StartBoundaryID': 1,
          'LaneNumber': 4,
          'BoundaryNumber': 7,
          'LaneAssetType': {'Boundary1': 'SW',
                            'Boundary2': 'SW',
                            'Boundary3': 'SW',
                            'Boundary4': 'SW',
                            'Boundary5': 'SW',
                            'Boundary6': 'SW',
                            'Boundary7': 'SW',
                            },  # boundary的个数根据组件类型得出
          'Function': '+',
          'K': '+',
          'Type': 'fork',
          'Flag': '单向双车道右弯曲岔路'}
# fork_dict14
dict14 = {'Start': (-60, -100),
          'W': 3.5,
          'R': 10,
          'StartLaneID': 1,
          'StartBoundaryID': 1,
          'LaneNumber': 4,
          'BoundaryNumber': 7,
          'LaneAssetType': {'Boundary1': 'SW',
                            'Boundary2': 'SY',
                            'Boundary3': 'SW',
                            'Boundary4': 'SW',
                            'Boundary5': 'SW',
                            'Boundary6': 'SW',
                            'Boundary7': 'SW',
                            },  # boundary的个数根据组件类型得出
          'Function': '+',
          'K': '+',
          'Type': 'fork',
          'Flag': '双向双车道右弯曲岔路'}

# fork_dict15
dict15 = {'Start': (-20, -100),
          'W': 3.5,
          'R': 10,
          'StartLaneID': 1,
          'StartBoundaryID': 1,
          'LaneNumber': 6,
          'BoundaryNumber': 9,
          'LaneAssetType': {'Boundary1': 'SW',
                            'Boundary2': 'DW',
                            'Boundary3': 'SY',
                            'Boundary4': 'SW',
                            'Boundary5': 'SW',
                            'Boundary6': 'DW',
                            'Boundary7': 'SW',
                            'Boundary8': 'SW',
                            'Boundary9': 'SW',
                            },  # boundary的个数根据组件类型得出
          'Function': '+',
          'K': '+',
          'Type': 'fork',
          'Flag': '一前行三车道右弯曲岔路'}
# fork_dict16
dict16 = {'Start': (20, -100),
          'W': 3.5,
          'R': 10,
          'StartLaneID': 1,
          'StartBoundaryID': 1,
          'LaneNumber': 6,
          'BoundaryNumber': 9,
          'LaneAssetType': {'Boundary1': 'SW',
                            'Boundary2': 'SY',
                            'Boundary3': 'DW',
                            'Boundary4': 'SW',
                            'Boundary5': 'SW',
                            'Boundary6': 'SY',
                            'Boundary7': 'SW',
                            'Boundary8': 'SW',
                            'Boundary9': 'SW',
                            },  # boundary的个数根据组件类型得出
          'Function': '+',
          'K': '+',
          'Type': 'fork',
          'Flag': '二前行三车道一右弯曲岔路'}
# fork_dict17
dict17 = {'Start': (60, -100),
          'W': 3.5,
          'R': 10,
          'StartLaneID': 1,
          'StartBoundaryID': 1,
          'LaneNumber': 6,
          'BoundaryNumber': 9,
          'LaneAssetType': {'Boundary1': 'SW',
                            'Boundary2': 'SY',
                            'Boundary3': 'DW',
                            'Boundary4': 'SW',
                            'Boundary5': 'SW',
                            'Boundary6': 'SW',
                            'Boundary7': 'SW',
                            'Boundary8': 'DW',
                            'Boundary9': 'SW',
                            },  # boundary的个数根据组件类型得出
          'Function': '+',
          'K': '+',
          'Type': 'fork',
          'Flag': '二前行三车道二右弯曲岔路'}
# fork_dict18
dict18 = {'Start': (100, -100),
          'W': 3.5,
          'R': 10,
          'StartLaneID': 1,
          'StartBoundaryID': 1,
          'LaneNumber': 6,
          'BoundaryNumber': 10,
          'LaneAssetType': {'Boundary1': 'SW',
                            'Boundary2': 'DW',
                            'Boundary3': 'SY',
                            'Boundary4': 'SW',
                            'Boundary5': 'SW',
                            'Boundary6': 'SW',
                            'Boundary7': 'SW',
                            'Boundary8': 'SW',
                            'Boundary9': 'SW',
                            'Boundary10': 'SW',
                            },  # boundary的个数根据组件类型得出
          'Function': '+',
          'K': '+',
          'Type': 'fork',
          'Flag': '一前行三车道左右弯曲岔路'}
# fork_dict19
dict19 = {'Start': (-100, -200),
          'W': 3.5,
          'R': 10,
          'StartLaneID': 1,
          'StartBoundaryID': 1,
          'LaneNumber': 6,
          'BoundaryNumber': 10,
          'LaneAssetType': {'Boundary1': 'SW',
                            'Boundary2': 'SY',
                            'Boundary3': 'DW',
                            'Boundary4': 'SW',
                            'Boundary5': 'SW',
                            'Boundary6': 'SW',
                            'Boundary7': 'SW',
                            'Boundary8': 'SW',
                            'Boundary9': 'SW',
                            'Boundary10': 'SW',
                            },  # boundary的个数根据组件类型得出
          'Function': '+',
          'K': '+',
          'Type': 'fork',
          'Flag': '二前行三车道左右弯曲岔路'}

# fork_dict20
dict20 = {'Start': (-60, -200),
          'W': 3.5,
          'R': 10,
          'StartLaneID': 1,
          'StartBoundaryID': 1,
          'LaneNumber': 8,
          'BoundaryNumber': 11,
          'LaneAssetType': {'Boundary1': 'SW',
                            'Boundary2': 'DW',
                            'Boundary3': 'SDY',
                            'Boundary4': 'DW',
                            'Boundary5': 'SW',
                            'Boundary6': 'SW',
                            'Boundary7': 'DW',
                            'Boundary8': 'SY',
                            'Boundary9': 'SW',
                            'Boundary10': 'SW',
                            'Boundary11': 'SW',
                            },  # boundary的个数根据组件类型得出
          'Function': '+',
          'K': '+',
          'Type': 'fork',
          'Flag': '四车道一右弯曲岔路'}
# fork_dict21
dict21 = {'Start': (-20, -200),
          'W': 3.5,
          'R': 10,
          'StartLaneID': 1,
          'StartBoundaryID': 1,
          'LaneNumber': 8,
          'BoundaryNumber': 11,
          'LaneAssetType': {'Boundary1': 'SW',
                            'Boundary2': 'DW',
                            'Boundary3': 'SDY',
                            'Boundary4': 'DW',
                            'Boundary5': 'SW',
                            'Boundary6': 'SW',
                            'Boundary7': 'DW',
                            'Boundary8': 'SW',
                            'Boundary9': 'SW',
                            'Boundary10': 'DW',
                            'Boundary11': 'SW',
                            },  # boundary的个数根据组件类型得出
          'Function': '+',
          'K': '+',
          'Type': 'fork',
          'Flag': '四车道二右弯曲岔路'}
# fork_dict22
dict22 = {'Start': (20, -200),
          'W': 3.5,
          'R': 10,
          'StartLaneID': 1,
          'StartBoundaryID': 1,
          'LaneNumber': 8,
          'BoundaryNumber': 12,
          'LaneAssetType': {'Boundary1': 'SW',
                            'Boundary2': 'DW',
                            'Boundary3': 'SDY',
                            'Boundary4': 'DW',
                            'Boundary5': 'SW',
                            'Boundary6': 'SW',
                            'Boundary7': 'SW',
                            'Boundary8': 'SW',
                            'Boundary9': 'SY',
                            'Boundary10': 'SW',
                            'Boundary11': 'SW',
                            'Boundary12': 'SW',
                            },  # boundary的个数根据组件类型得出
          'Function': '+',
          'K': '+',
          'Type': 'fork',
          'Flag': '四车道左右弯曲岔路'}
