# laneswitch_dict1
dict1 = {'Start': (-60, 0),
         'W': 3.5,
         'LaneNumber': 5,
         'BoundaryNumber': 8,
         'LaneAssetType': {'Boundary1': 'SW',
                           'Boundary2': 'SW',
                           'Boundary3': 'SW',
                           'Boundary4': 'DW',
                           'Boundary5': 'SW',
                           'Boundary6': 'SW',
                           'Boundary7': 'DW',
                           'Boundary8': 'SW'},  # boundary的个数根据组件类型得出
         'Function': '+',
         'K': '+',
         'Type': 'laneswitch',
         'Flag': '1*2左',
         'NextType': '单向虚线双行道'
         }
# laneswitch_dict13
dict13 = {'Start': (-60, 0),
          'W': 3.5,
          'LaneNumber': 5,
          'BoundaryNumber': 8,
          'LaneAssetType': {'Boundary1': 'SW',
                            'Boundary2': 'SW',
                            'Boundary3': 'SW',
                            'Boundary4': 'DW',
                            'Boundary5': 'SW',
                            'Boundary6': 'SW',
                            'Boundary7': 'DW',
                            'Boundary8': 'SW'},  # boundary的个数根据组件类型得出
          'Function': '+',
          'K': '+',
          'Flag': '1*2右',
          'Type': 'laneswitch',
          'NextType': '单向虚线双行道'
          }

# laneswitch_dict12
dict2 = {'Start': (-40, 0),
         'W': 3.5,
         'LaneNumber': 5,
         'BoundaryNumber': 8,
         'LaneAssetType': {'Boundary1': 'SW',
                           'Boundary2': 'DW',
                           'Boundary3': 'SW',
                           'Boundary4': 'SW',
                           'Boundary5': 'DW',
                           'Boundary6': 'SW',
                           'Boundary7': 'SW',
                           'Boundary8': 'SW'},  # boundary的个数根据组件类型得出
         'Function': '+',
         'K': '+',
         'Flag': '2*1左',
         'Type': 'laneswitch',
         'NextType': '单行道'
         }
# laneswitch_dict14
dict14 = {'Start': (-40, 0),
          'W': 3.5,
          'LaneNumber': 5,
          'BoundaryNumber': 8,
          'LaneAssetType': {'Boundary1': 'SW',
                            'Boundary2': 'DW',
                            'Boundary3': 'SW',
                            'Boundary4': 'SW',
                            'Boundary5': 'DW',
                            'Boundary6': 'SW',
                            'Boundary7': 'SW',
                            'Boundary8': 'SW'},  # boundary的个数根据组件类型得出
          'Function': '+',
          'K': '+',
          'Flag': '2*1右',
          'Type': 'laneswitch',
          'NextType': '单行道'
          }

# laneswitch_dict3
dict3 = {'Start': (-20, 0),
         'W': 3.5,
         'LaneNumber': 8,
         'BoundaryNumber': 11,
         'LaneAssetType': {'Boundary1': 'SW',
                           'Boundary2': 'SY',
                           'Boundary3': 'SW',
                           'Boundary4': 'SW',
                           'Boundary5': 'DW',
                           'Boundary6': 'SY',
                           'Boundary7': 'SW',
                           'Boundary8': 'SW',
                           'Boundary9': 'DW',
                           'Boundary10': 'SY',
                           'Boundary11': 'SW', },  # boundary的个数根据组件类型得出
         'Function': '+',
         'K': '+',
         'Flag': '2*3左',
         'Type': 'laneswitch',
         'NextType': '一前行虚白线实黄线三行道'
         }
# laneswitch_dict4
dict4 = {'Start': (0, 0),
         'W': 3.5,
         'LaneNumber': 8,
         'BoundaryNumber': 11,
         'LaneAssetType': {'Boundary1': 'SW',
                           'Boundary2': 'SY',
                           'Boundary3': 'SW',
                           'Boundary4': 'SW',
                           'Boundary5': 'SY',
                           'Boundary6': 'DW',
                           'Boundary7': 'SW',
                           'Boundary8': 'SW',
                           'Boundary9': 'SY',
                           'Boundary10': 'DW',
                           'Boundary11': 'SW', },  # boundary的个数根据组件类型得出
         'Function': '+',
         'K': '+',
         'Flag': '2*3右',
         'Type': 'laneswitch',
         'NextType': '二前行实黄线虚白线三行道'
         }
# laneswitch_dict5
#一前行
dict5 = {'Start': (20, 0),
         'W': 3.5,
         'LaneNumber': 8,
         'BoundaryNumber': 11,
         'LaneAssetType': {'Boundary1': 'SW',
                           'Boundary2': 'DW',
                           'Boundary3': 'SY',
                           'Boundary4': 'SW',
                           'Boundary5': 'SW',
                           'Boundary6': 'DW',
                           'Boundary7': 'SY',
                           'Boundary8': 'SW',
                           'Boundary9': 'SW',
                           'Boundary10': 'SY',
                           'Boundary11': 'SW', },  # boundary的个数根据组件类型得出
         'Function': '+',
         'K': '+',
         'Flag': '3*2左',
         'Type': 'laneswitch',
         'NextType': '双向虚线双行道'
         }
# laneswitch_dict6
#二前行
dict6 = {'Start': (40, 0),
         'W': 3.5,
         'LaneNumber': 8,
         'BoundaryNumber': 11,
         'LaneAssetType': {'Boundary1': 'SW',
                           'Boundary2': 'SY',
                           'Boundary3': 'DW',
                           'Boundary4': 'SW',
                           'Boundary5': 'SW',
                           'Boundary6': 'SY',
                           'Boundary7': 'DW',
                           'Boundary8': 'SW',
                           'Boundary9': 'SW',
                           'Boundary10': 'SY',
                           'Boundary11': 'SW', },  # boundary的个数根据组件类型得出
         'Function': '+',
         'K': '+',
         'Flag': '3*2右',
         'Type': 'laneswitch',
         'NextType': '双向虚线双行道'
         }
# laneswitch_dict7
#一前行
dict7 = {'Start': (-60, -50),
         'W': 3.5,
         'LaneNumber': 11,
         'BoundaryNumber': 14,
         'LaneAssetType': {'Boundary1': 'SW',
                           'Boundary2': 'DW',
                           'Boundary3': 'SY',
                           'Boundary4': 'SW',
                           'Boundary5': 'SW',
                           'Boundary6': 'DW',
                           'Boundary7': 'SDY',
                           'Boundary8': 'DW',
                           'Boundary9': 'SW',
                           'Boundary10': 'SW',
                           'Boundary11': 'DW',
                           'Boundary12': 'SDY',
                           'Boundary13': 'DW',
                           'Boundary14': 'SW',
                           },  # boundary的个数根据组件类型得出
         'Function': '+',
         'K': '+',
         'Flag': '3*4右',
         'Type': 'laneswitch',
         'NextType': '双黄实线虚虚四车道'
         }
# laneswitch_dict8
#二前行
dict8 = {'Start': (-40, -50),
         'W': 3.5,
         'LaneNumber': 11,
         'BoundaryNumber': 14,
         'LaneAssetType': {'Boundary1': 'SW',
                           'Boundary2': 'SY',
                           'Boundary3': 'DW',
                           'Boundary4': 'SW',
                           'Boundary5': 'SW',
                           'Boundary6': 'DW',
                           'Boundary7': 'SDY',
                           'Boundary8': 'DW',
                           'Boundary9': 'SW',
                           'Boundary10': 'SW',
                           'Boundary11': 'DW',
                           'Boundary12': 'SDY',
                           'Boundary13': 'DW',
                           'Boundary14': 'SW',
                           },  # boundary的个数根据组件类型得出
         'Function': '+',
         'K': '+',
         'Flag': '3*4左',
         'Type': 'laneswitch',
         'NextType': '双黄实线虚虚四车道'
         }
# laneswitch_dict9
dict9 = {'Start': (-20, -50),
         'W': 3.5,
         'LaneNumber': 11,
         'BoundaryNumber': 14,
         'LaneAssetType': {'Boundary1': 'SW',
                           'Boundary2': 'DW',
                           'Boundary3': 'SDY',
                           'Boundary4': 'DW',
                           'Boundary5': 'SW',
                           'Boundary6': 'SW',
                           'Boundary7': 'DW',
                           'Boundary8': 'SDY',
                           'Boundary9': 'DW',
                           'Boundary10': 'SW',
                           'Boundary11': 'SW',
                           'Boundary12': 'SY',
                           'Boundary13': 'DW',
                           'Boundary14': 'SW',
                           },  # boundary的个数根据组件类型得出
         'Function': '+',
         'K': '+',
         'Flag': '4*3左',
         'Type': 'laneswitch',
         'NextType': '二前行实黄线虚白线三行道'
         }
# laneswitch_dict10
dict10 = {'Start': (0, -50),
          'W': 3.5,
          'LaneNumber': 11,
          'BoundaryNumber': 14,
          'LaneAssetType': {'Boundary1': 'SW',
                            'Boundary2': 'DW',
                            'Boundary3': 'SDY',
                            'Boundary4': 'DW',
                            'Boundary5': 'SW',
                            'Boundary6': 'SW',
                            'Boundary7': 'DW',
                            'Boundary8': 'SDY',
                            'Boundary9': 'DW',
                            'Boundary10': 'SW',
                            'Boundary11': 'SW',
                            'Boundary12': 'DW',
                            'Boundary13': 'SY',
                            'Boundary14': 'SW',
                            },  # boundary的个数根据组件类型得出
          'Function': '+',
          'K': '+',
          'Flag': '4*3右',
          'Type': 'laneswitch',
          'NextType': '一前行虚白线实黄线三行道'
          }
# laneswitch_dict11
dict11 = {'Start': (20, -50),
          'W': 3.5,
          'LaneNumber': 16,
          'BoundaryNumber': 19,
          'LaneAssetType': {'Boundary1': 'SW',
                            'Boundary2': 'DW',
                            'Boundary3': 'SDY',
                            'Boundary4': 'DW',
                            'Boundary5': 'SW',
                            'Boundary6': 'SW',
                            'Boundary7': 'DW',
                            'Boundary8': 'DW',
                            'Boundary9': 'SDY',
                            'Boundary10': 'DW',
                            'Boundary11': 'DW',
                            'Boundary12': 'SW',
                            'Boundary13': 'SW',
                            'Boundary14': 'DW',
                            'Boundary15': 'DW',
                            'Boundary16': 'SDY',
                            'Boundary17': 'DW',
                            'Boundary18': 'DW',
                            'Boundary19': 'SW',
                            },  # boundary的个数根据组件类型得出
          'Function': '+',
          'K': '+',
          'Flag': '4*6',
          'Type': 'laneswitch',
          'NextType': '双实线虚虚虚虚六车道'
          }
# laneswitch_dict12
dict12 = {'Start': (40, -50),
          'W': 3.5,
          'LaneNumber': 16,
          'BoundaryNumber': 19,
          'LaneAssetType': {'Boundary1': 'SW',
                            'Boundary2': 'DW',
                            'Boundary3': 'DW',
                            'Boundary4': 'SDY',
                            'Boundary5': 'DW',
                            'Boundary6': 'DW',
                            'Boundary7': 'SW',
                            'Boundary8': 'SW',
                            'Boundary9': 'DW',
                            'Boundary10': 'DW',
                            'Boundary11': 'SDY',
                            'Boundary12': 'DW',
                            'Boundary13': 'DW',
                            'Boundary14': 'SW',
                            'Boundary15': 'SW',
                            'Boundary16': 'DW',
                            'Boundary17': 'SDY',
                            'Boundary18': 'DW',
                            'Boundary19': 'SW',
                            },  # boundary的个数根据组件类型得出
          'Function': '+',
          'K': '+',
          'Flag': '6*4',
          'Type': 'laneswitch',
          'NextType': '双黄实线虚虚四车道'
          }
