dict1_0 = {'Start': (0, 0),
           'LW': (20, 3.5),
           'DX': (10, 5),
           'LaneNumber': 3,
           'BoundaryNumber': 6,
           'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SW', 'Boundary3': 'SW', 'Boundary4': 'SW',
                             'Boundary5': 'SW', 'Boundary6': 'SW'},
           'Direction': 0,
           'Function': '+',
           'K': '+',
           'Type': 'ulane',
           'Flag': '单行道'}
dict2_0 = {'Start': (0, 0),
           'LW': (20, 3.5),
           'DX': (10, 5),
           'LaneNumber': 6,
           'BoundaryNumber': 9,
           'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DW', 'Boundary3': 'SW', 'Boundary4': 'SW',
                             'Boundary5': 'DW', 'Boundary6': 'SW', 'Boundary7': 'SW',
                             'Boundary8': 'DW', 'Boundary9': 'SW'},
           'Direction': 0,
           'Function': '+',
           'K': '-0',
           'Type': 'ulane',
           'Flag': '单向虚线双行道'}
dict3_0 = {'Start': (0, 0),
           'LW': (20, 3.5),
           'DX': (10, 5),
           'LaneNumber': 6,
           'BoundaryNumber': 9,
           'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SW', 'Boundary3': 'SW', 'Boundary4': 'SW',
                             'Boundary5': 'SW', 'Boundary6': 'SW', 'Boundary7': 'SW',
                             'Boundary8': 'SW', 'Boundary9': 'SW'},
           'Direction': 0,
           'Function': '+',
           'K': '-0',
           'Type': 'ulane',
           'Flag': '单向实线双行道'}
dict4_0 = {'Start': (0, 0),
           'LW': (20, 3.5),
           'DX': (10, 5),
           'LaneNumber': 6,
           'BoundaryNumber': 9,
           'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DSW', 'Boundary3': 'SW', 'Boundary4': 'SW',
                             'Boundary5': 'DSW', 'Boundary6': 'SW', 'Boundary7': 'SW',
                             'Boundary8': 'DSW', 'Boundary9': 'SW'},
           'Direction': 0,
           'Function': '+',
           'K': '-0',
           'Type': 'ulane',
           'Flag': '单向虚实线双行道'}

dict5_0 = {'Start': (0, 0),
           'LW': (20, 3.5),
           'DX': (10, 5),
           'LaneNumber': 6,
           'BoundaryNumber': 9,
           'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SDW', 'Boundary3': 'SW', 'Boundary4': 'SW',
                             'Boundary5': 'SDW', 'Boundary6': 'SW', 'Boundary7': 'SW',
                             'Boundary8': 'SDW', 'Boundary9': 'SW'},
           'Direction': 0,
           'Function': '+',
           'K': '-0',
           'Type': 'ulane',
           'Flag': '单向双实线双行道'}

dict6_0 = {'Start': (0, 0),
           'LW': (20, 3.5),
           'DX': (10, 5),
           'LaneNumber': 6,
           'BoundaryNumber': 9,
           'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DW', 'Boundary3': 'SW', 'Boundary4': 'SW',
                             'Boundary5': 'DW', 'Boundary6': 'SW', 'Boundary7': 'SW',
                             'Boundary8': 'DW', 'Boundary9': 'SW'},
           'Direction': 0,
           'Function': '+',
           'K': '-0',
           'Type': 'ulane',
           'Flag': '双向虚线双行道'}

dict7_0 = {'Start': (0, 0),
           'LW': (20, 3.5),
           'DX': (10, 5),
           'LaneNumber': 6,
           'BoundaryNumber': 9,
           'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SW', 'Boundary3': 'SW', 'Boundary4': 'SW',
                             'Boundary5': 'SW', 'Boundary6': 'SW', 'Boundary7': 'SW',
                             'Boundary8': 'SW', 'Boundary9': 'SW'},
           'Direction': 0,
           'Function': '+',
           'K': '-0',
           'Type': 'ulane',
           'Flag': '双向实线双行道'}

dict8_0 = {'Start': (0, 0),
           'LW': (20, 3.5),
           'DX': (10, 5),
           'LaneNumber': 6,
           'BoundaryNumber': 9,
           'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DSW', 'Boundary3': 'SW', 'Boundary4': 'SW',
                             'Boundary5': 'DSW', 'Boundary6': 'SW', 'Boundary7': 'SW',
                             'Boundary8': 'DSW', 'Boundary9': 'SW'},
           'Direction': 0,
           'Function': '+',
           'K': '-0',
           'Type': 'ulane',
           'Flag': '双向虚实线双行道'}

dict9_0 = {'Start': (0, 0),
           'LW': (20, 3.5),
           'DX': (10, 5),
           'LaneNumber': 6,
           'BoundaryNumber': 9,
           'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SDW', 'Boundary3': 'SW', 'Boundary4': 'SW',
                             'Boundary5': 'SDW', 'Boundary6': 'SW', 'Boundary7': 'SW',
                             'Boundary8': 'SDW', 'Boundary9': 'SW'},
           'Direction': 0,
           'Function': '+',
           'K': '-0',
           'Type': 'ulane',
           'Flag': '双向双实线双行道'}

dict10_0 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 9,
            'BoundaryNumber': 12,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DW', 'Boundary3': 'DY', 'Boundary4': 'SW',
                              'Boundary5': 'SW', 'Boundary6': 'DW', 'Boundary7': 'DY',
                              'Boundary8': 'SW', 'Boundary9': 'SW', 'Boundary10': 'DW', 'Boundary11': 'DY',
                              'Boundary12': 'SW'},
            'Direction': 0,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '一前行虚白线虚黄线三行道'}
dict11_0 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 9,
            'BoundaryNumber': 12,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SW', 'Boundary3': 'DY', 'Boundary4': 'SW',
                              'Boundary5': 'SW', 'Boundary6': 'SW', 'Boundary7': 'DY',
                              'Boundary8': 'SW', 'Boundary9': 'SW', 'Boundary10': 'SW', 'Boundary11': 'DY',
                              'Boundary12': 'SW'},
            'Direction': 0,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '一前行实白线虚黄线三行道'}
dict12_0 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 9,
            'BoundaryNumber': 12,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DW', 'Boundary3': 'SY', 'Boundary4': 'SW',
                              'Boundary5': 'SW', 'Boundary6': 'DW', 'Boundary7': 'SY',
                              'Boundary8': 'SW', 'Boundary9': 'SW', 'Boundary10': 'DW', 'Boundary11': 'SY',
                              'Boundary12': 'SW'},
            'Direction': 0,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '一前行虚白线实黄线三行道'}
dict13_0 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 9,
            'BoundaryNumber': 12,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SW', 'Boundary3': 'SY', 'Boundary4': 'SW',
                              'Boundary5': 'SW', 'Boundary6': 'SW', 'Boundary7': 'SY',
                              'Boundary8': 'SW', 'Boundary9': 'SW', 'Boundary10': 'SW', 'Boundary11': 'SY',
                              'Boundary12': 'SW'},
            'Direction': 0,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '一前行实白线实黄线三行道'}

dict14_0 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 9,
            'BoundaryNumber': 12,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DY', 'Boundary3': 'DW', 'Boundary4': 'SW',
                              'Boundary5': 'SW', 'Boundary6': 'DY', 'Boundary7': 'DW',
                              'Boundary8': 'SW', 'Boundary9': 'SW', 'Boundary10': 'DY', 'Boundary11': 'DW',
                              'Boundary12': 'SW'},
            'Direction': 0,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '二前行虚黄线虚白线三行道'}

dict15_0 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 9,
            'BoundaryNumber': 12,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DY', 'Boundary3': 'SW', 'Boundary4': 'SW',
                              'Boundary5': 'SW', 'Boundary6': 'DY', 'Boundary7': 'SW',
                              'Boundary8': 'SW', 'Boundary9': 'SW', 'Boundary10': 'DY', 'Boundary11': 'SW',
                              'Boundary12': 'SW'},
            'Direction': 0,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '二前行虚黄线实白线三行道'}
dict16_0 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 9,
            'BoundaryNumber': 12,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SY', 'Boundary3': 'DW', 'Boundary4': 'SW',
                              'Boundary5': 'SW', 'Boundary6': 'SY', 'Boundary7': 'DW',
                              'Boundary8': 'SW', 'Boundary9': 'SW', 'Boundary10': 'SY', 'Boundary11': 'DW',
                              'Boundary12': 'SW'},
            'Direction': 0,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '二前行实黄线虚白线三行道'}
dict17_0 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'StartLaneID': 1,
            'StartBoundaryID': 1,
            'LaneNumber': 9,
            'BoundaryNumber': 12,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SY', 'Boundary3': 'SW', 'Boundary4': 'SW',
                              'Boundary5': 'SW', 'Boundary6': 'SY', 'Boundary7': 'SW',
                              'Boundary8': 'SW', 'Boundary9': 'SW', 'Boundary10': 'SY', 'Boundary11': 'SW',
                              'Boundary12': 'SW'},
            'Direction': 0,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '二前行实黄线实白线三行道'}

dict18_0 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 12,
            'BoundaryNumber': 15,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DW', 'Boundary3': 'SDY', 'Boundary4': 'DW',
                              'Boundary5': 'SW',
                              'Boundary6': 'SW', 'Boundary7': 'DW', 'Boundary8': 'SDY', 'Boundary9': 'DW',
                              'Boundary10': 'SW',
                              'Boundary11': 'SW', 'Boundary12': 'DW', 'Boundary13': 'SDY', 'Boundary14': 'DW',
                              'Boundary15': 'SW'},
            'Direction': 0,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '双黄实线虚虚四车道'}
dict19_0 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 12,
            'BoundaryNumber': 15,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SW', 'Boundary3': 'SDY', 'Boundary4': 'SW',
                              'Boundary5': 'SW',
                              'Boundary6': 'SW', 'Boundary7': 'SW', 'Boundary8': 'SDY', 'Boundary9': 'SW',
                              'Boundary10': 'SW',
                              'Boundary11': 'SW', 'Boundary12': 'SW', 'Boundary13': 'SDY', 'Boundary14': 'SW',
                              'Boundary15': 'SW'},
            'Direction': 0,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '双黄实线实实四车道'}
dict20_0 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 12,
            'BoundaryNumber': 15,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DW', 'Boundary3': 'SDY', 'Boundary4': 'SW',
                              'Boundary5': 'SW',
                              'Boundary6': 'SW', 'Boundary7': 'DW', 'Boundary8': 'SDY', 'Boundary9': 'SW',
                              'Boundary10': 'SW',
                              'Boundary11': 'SW', 'Boundary12': 'DW', 'Boundary13': 'SDY', 'Boundary14': 'SW',
                              'Boundary15': 'SW'},
            'Direction': 0,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '双黄实线虚实四车道'}
dict21_0 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 12,
            'BoundaryNumber': 15,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SW', 'Boundary3': 'SDY', 'Boundary4': 'DW',
                              'Boundary5': 'SW',
                              'Boundary6': 'SW', 'Boundary7': 'SW', 'Boundary8': 'SDY', 'Boundary9': 'DW',
                              'Boundary10': 'SW',
                              'Boundary11': 'SW', 'Boundary12': 'SW', 'Boundary13': 'SDY', 'Boundary14': 'DW',
                              'Boundary15': 'SW'},
            'Direction': 0,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '双黄实线虚实四车道'}

dict22_0 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 18,
            'BoundaryNumber': 21,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DW', 'Boundary3': 'DW', 'Boundary4': 'SDY',
                              'Boundary5': 'DW', 'Boundary6': 'DW', 'Boundary7': 'SW',
                              'Boundary8': 'SW', 'Boundary9': 'DW', 'Boundary10': 'DW', 'Boundary11': 'SDY',
                              'Boundary12': 'DW', 'Boundary13': 'DW', 'Boundary14': 'SW',
                              'Boundary15': 'SW', 'Boundary16': 'DW', 'Boundary17': 'DW', 'Boundary18': 'SDY',
                              'Boundary19': 'DW', 'Boundary20': 'DW', 'Boundary21': 'SW'},
            'Direction': 0,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '双实线虚虚虚虚六车道'}
dict23_0 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 18,
            'BoundaryNumber': 21,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SW', 'Boundary3': 'SW', 'Boundary4': 'SDY',
                              'Boundary5': 'SW', 'Boundary6': 'SW', 'Boundary7': 'SW',
                              'Boundary8': 'SW', 'Boundary9': 'SW', 'Boundary10': 'SW', 'Boundary11': 'SDY',
                              'Boundary12': 'SW', 'Boundary13': 'SW', 'Boundary14': 'SW',
                              'Boundary15': 'SW', 'Boundary16': 'SW', 'Boundary17': 'SW', 'Boundary18': 'SDY',
                              'Boundary19': 'SW', 'Boundary20': 'SW', 'Boundary21': 'SW'},
            'Direction': 0,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '双实线实实实实六车道'}
dict24_0 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 18,
            'BoundaryNumber': 21,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DW', 'Boundary3': 'DW', 'Boundary4': 'SDY',
                              'Boundary5': 'SW', 'Boundary6': 'SW', 'Boundary7': 'SW',
                              'Boundary8': 'SW', 'Boundary9': 'DW', 'Boundary10': 'DW', 'Boundary11': 'SDY',
                              'Boundary12': 'SW', 'Boundary13': 'SW', 'Boundary14': 'SW',
                              'Boundary15': 'SW', 'Boundary16': 'DW', 'Boundary17': 'DW', 'Boundary18': 'SDY',
                              'Boundary19': 'SW', 'Boundary20': 'SW', 'Boundary21': 'SW'},
            'Direction': 0,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '双实线虚虚实实六车道'}

dict1_1 = {'Start': (0, 0),
           'LW': (20, 3.5),
           'DX': (10, 5),
           'LaneNumber': 3,
           'BoundaryNumber': 6,
           'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SW', 'Boundary3': 'SW', 'Boundary4': 'SW',
                             'Boundary5': 'SW', 'Boundary6': 'SW'},
           'Direction': 1,
           'Function': '+',
           'K': '-',
           'Type': 'ulane',
           'Flag': '单行道'}

dict2_1 = {'Start': (0, 0),
           'LW': (20, 3.5),
           'DX': (10, 5),
           'LaneNumber': 6,
           'BoundaryNumber': 9,
           'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DW', 'Boundary3': 'SW', 'Boundary4': 'SW',
                             'Boundary5': 'DW', 'Boundary6': 'SW', 'Boundary7': 'SW',
                             'Boundary8': 'DW', 'Boundary9': 'SW'},
           'Direction': 1,
           'Function': '+',
           'K': '-0',
           'Type': 'ulane',
           'Flag': '单向虚线双行道'}
dict3_1 = {'Start': (0, 0),
           'LW': (20, 3.5),
           'DX': (10, 5),
           'LaneNumber': 6,
           'BoundaryNumber': 9,
           'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SW', 'Boundary3': 'SW', 'Boundary4': 'SW',
                             'Boundary5': 'SW', 'Boundary6': 'SW', 'Boundary7': 'SW',
                             'Boundary8': 'SW', 'Boundary9': 'SW'},
           'Direction': 1,
           'Function': '+',
           'K': '-0',
           'Type': 'ulane',
           'Flag': '单向实线双行道'}

dict4_1 = {'Start': (0, 0),
           'LW': (20, 3.5),
           'DX': (10, 5),
           'LaneNumber': 6,
           'BoundaryNumber': 9,
           'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DSW', 'Boundary3': 'SW', 'Boundary4': 'SW',
                             'Boundary5': 'DSW', 'Boundary6': 'SW', 'Boundary7': 'SW',
                             'Boundary8': 'DSW', 'Boundary9': 'SW'},
           'Direction': 1,
           'Function': '+',
           'K': '-0',
           'Type': 'ulane',
           'Flag': '单向虚实线双行道'}

dict5_1 = {'Start': (0, 0),
           'LW': (20, 3.5),
           'DX': (10, 5),
           'LaneNumber': 6,
           'BoundaryNumber': 9,
           'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SDW', 'Boundary3': 'SW', 'Boundary4': 'SW',
                             'Boundary5': 'SDW', 'Boundary6': 'SW', 'Boundary7': 'SW',
                             'Boundary8': 'SDW', 'Boundary9': 'SW'},
           'Direction': 1,
           'Function': '+',
           'K': '-0',
           'Type': 'ulane',
           'Flag': '单向双实线双行道'}

dict6_1 = {'Start': (0, 0),
           'LW': (20, 3.5),
           'DX': (10, 5),
           'LaneNumber': 6,
           'BoundaryNumber': 9,
           'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DW', 'Boundary3': 'SW', 'Boundary4': 'SW',
                             'Boundary5': 'DW', 'Boundary6': 'SW', 'Boundary7': 'SW',
                             'Boundary8': 'DW', 'Boundary9': 'SW'},
           'Direction': 1,
           'Function': '+',
           'K': '-0',
           'Type': 'ulane',
           'Flag': '双向虚线双行道'}

dict7_1 = {'Start': (0, 0),
           'LW': (20, 3.5),
           'DX': (10, 5),
           'LaneNumber': 6,
           'BoundaryNumber': 9,
           'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SW', 'Boundary3': 'SW', 'Boundary4': 'SW',
                             'Boundary5': 'SW', 'Boundary6': 'SW', 'Boundary7': 'SW',
                             'Boundary8': 'SW', 'Boundary9': 'SW'},
           'Direction': 1,
           'Function': '+',
           'K': '-0',
           'Type': 'ulane',
           'Flag': '双向实线双行道'}
# ulane_dict7
dict8_1 = {'Start': (0, 0),
           'LW': (20, 3.5),
           'DX': (10, 5),
           'LaneNumber': 6,
           'BoundaryNumber': 9,
           'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DSW', 'Boundary3': 'SW', 'Boundary4': 'SW',
                             'Boundary5': 'DSW', 'Boundary6': 'SW', 'Boundary7': 'SW',
                             'Boundary8': 'DSW', 'Boundary9': 'SW'},
           'Direction': 1,
           'Function': '+',
           'K': '-0',
           'Type': 'ulane',
           'Flag': '双向虚实线双行道'}
# ulane_dict8
dict9_1 = {'Start': (0, 0),
           'LW': (20, 3.5),
           'DX': (10, 5),
           'LaneNumber': 6,
           'BoundaryNumber': 9,
           'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SDW', 'Boundary3': 'SW', 'Boundary4': 'SW',
                             'Boundary5': 'SDW', 'Boundary6': 'SW', 'Boundary7': 'SW',
                             'Boundary8': 'SDW', 'Boundary9': 'SW'},
           'Direction': 1,
           'Function': '+',
           'K': '-0',
           'Type': 'ulane',
           'Flag': '双向双实线双行道'}
# straight_dict9
dict10_1 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 9,
            'BoundaryNumber': 12,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DW', 'Boundary3': 'DY', 'Boundary4': 'SW',
                              'Boundary5': 'SW', 'Boundary6': 'DW', 'Boundary7': 'DY',
                              'Boundary8': 'SW', 'Boundary9': 'SW', 'Boundary10': 'DW', 'Boundary11': 'DY',
                              'Boundary12': 'SW'},
            'Direction': 1,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '一前行虚白线虚黄线三行道'}
dict11_1 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 9,
            'BoundaryNumber': 12,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SW', 'Boundary3': 'DY', 'Boundary4': 'SW',
                              'Boundary5': 'SW', 'Boundary6': 'SW', 'Boundary7': 'DY',
                              'Boundary8': 'SW', 'Boundary9': 'SW', 'Boundary10': 'SW', 'Boundary11': 'DY',
                              'Boundary12': 'SW'},
            'Direction': 1,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '一前行实白线虚黄线三行道'}
dict12_1 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 9,
            'BoundaryNumber': 12,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DW', 'Boundary3': 'SY', 'Boundary4': 'SW',
                              'Boundary5': 'SW', 'Boundary6': 'DW', 'Boundary7': 'SY',
                              'Boundary8': 'SW', 'Boundary9': 'SW', 'Boundary10': 'DW', 'Boundary11': 'SY',
                              'Boundary12': 'SW'},
            'Direction': 1,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '一前行虚白线实黄线三行道'}
dict13_1 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 9,
            'BoundaryNumber': 12,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SW', 'Boundary3': 'SY', 'Boundary4': 'SW',
                              'Boundary5': 'SW', 'Boundary6': 'SW', 'Boundary7': 'SY',
                              'Boundary8': 'SW', 'Boundary9': 'SW', 'Boundary10': 'SW', 'Boundary11': 'SY',
                              'Boundary12': 'SW'},
            'Direction': 1,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '一前行实白线实黄线三行道'}

dict14_1 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 9,
            'BoundaryNumber': 12,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DY', 'Boundary3': 'DW', 'Boundary4': 'SW',
                              'Boundary5': 'SW', 'Boundary6': 'DY', 'Boundary7': 'DW',
                              'Boundary8': 'SW', 'Boundary9': 'SW', 'Boundary10': 'DY', 'Boundary11': 'DW',
                              'Boundary12': 'SW'},
            'Direction': 1,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '二前行虚黄线虚白线三行道'}

dict15_1 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 9,
            'BoundaryNumber': 12,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DY', 'Boundary3': 'SW', 'Boundary4': 'SW',
                              'Boundary5': 'SW', 'Boundary6': 'DY', 'Boundary7': 'SW',
                              'Boundary8': 'SW', 'Boundary9': 'SW', 'Boundary10': 'DY', 'Boundary11': 'SW',
                              'Boundary12': 'SW'},
            'Direction': 1,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '二前行虚黄线实白线三行道'}
dict16_1 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 9,
            'BoundaryNumber': 12,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SY', 'Boundary3': 'DW', 'Boundary4': 'SW',
                              'Boundary5': 'SW', 'Boundary6': 'SY', 'Boundary7': 'DW',
                              'Boundary8': 'SW', 'Boundary9': 'SW', 'Boundary10': 'SY', 'Boundary11': 'DW',
                              'Boundary12': 'SW'},
            'Direction': 1,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '二前行实黄线虚白线三行道'}
dict17_1 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 9,
            'BoundaryNumber': 12,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SY', 'Boundary3': 'SW', 'Boundary4': 'SW',
                              'Boundary5': 'SW', 'Boundary6': 'SY', 'Boundary7': 'SW',
                              'Boundary8': 'SW', 'Boundary9': 'SW', 'Boundary10': 'SY', 'Boundary11': 'SW',
                              'Boundary12': 'SW'},
            'Direction': 1,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '二前行实黄线实白线三行道'}

dict18_1 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 12,
            'BoundaryNumber': 15,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DW', 'Boundary3': 'SDY', 'Boundary4': 'DW',
                              'Boundary5': 'SW',
                              'Boundary6': 'SW', 'Boundary7': 'DW', 'Boundary8': 'SDY', 'Boundary9': 'DW',
                              'Boundary10': 'SW',
                              'Boundary11': 'SW', 'Boundary12': 'DW', 'Boundary13': 'SDY', 'Boundary14': 'DW',
                              'Boundary15': 'SW'},
            'Direction': 1,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '双黄实线虚虚四车道'}
dict19_1 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 12,
            'BoundaryNumber': 15,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SW', 'Boundary3': 'SDY', 'Boundary4': 'SW',
                              'Boundary5': 'SW',
                              'Boundary6': 'SW', 'Boundary7': 'SW', 'Boundary8': 'SDY', 'Boundary9': 'SW',
                              'Boundary10': 'SW',
                              'Boundary11': 'SW', 'Boundary12': 'SW', 'Boundary13': 'SDY', 'Boundary14': 'SW',
                              'Boundary15': 'SW'},
            'Direction': 1,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '双黄实线实实四车道'}
dict20_1 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 12,
            'BoundaryNumber': 15,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DW', 'Boundary3': 'SDY', 'Boundary4': 'SW',
                              'Boundary5': 'SW',
                              'Boundary6': 'SW', 'Boundary7': 'DW', 'Boundary8': 'SDY', 'Boundary9': 'SW',
                              'Boundary10': 'SW',
                              'Boundary11': 'SW', 'Boundary12': 'DW', 'Boundary13': 'SDY', 'Boundary14': 'SW',
                              'Boundary15': 'SW'},
            'Direction': 1,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '双黄实线虚实四车道'}
dict21_1 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 12,
            'BoundaryNumber': 15,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SW', 'Boundary3': 'SDY', 'Boundary4': 'DW',
                              'Boundary5': 'SW',
                              'Boundary6': 'SW', 'Boundary7': 'SW', 'Boundary8': 'SDY', 'Boundary9': 'DW',
                              'Boundary10': 'SW',
                              'Boundary11': 'SW', 'Boundary12': 'SW', 'Boundary13': 'SDY', 'Boundary14': 'DW',
                              'Boundary15': 'SW'},
            'Direction': 1,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '双黄实线虚实四车道'}

dict22_1 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 18,
            'BoundaryNumber': 21,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DW', 'Boundary3': 'DW', 'Boundary4': 'SDY',
                              'Boundary5': 'DW', 'Boundary6': 'DW', 'Boundary7': 'SW',
                              'Boundary8': 'SW', 'Boundary9': 'DW', 'Boundary10': 'DW', 'Boundary11': 'SDY',
                              'Boundary12': 'DW', 'Boundary13': 'DW', 'Boundary14': 'SW',
                              'Boundary15': 'SW', 'Boundary16': 'DW', 'Boundary17': 'DW', 'Boundary18': 'SDY',
                              'Boundary19': 'DW', 'Boundary20': 'DW', 'Boundary21': 'SW'},
            'Direction': 1,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '双实线虚虚虚虚六车道'}
dict23_1 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 18,
            'BoundaryNumber': 21,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'SW', 'Boundary3': 'SW', 'Boundary4': 'SDY',
                              'Boundary5': 'SW', 'Boundary6': 'SW', 'Boundary7': 'SW',
                              'Boundary8': 'SW', 'Boundary9': 'SW', 'Boundary10': 'SW', 'Boundary11': 'SDY',
                              'Boundary12': 'SW', 'Boundary13': 'SW', 'Boundary14': 'SW',
                              'Boundary15': 'SW', 'Boundary16': 'SW', 'Boundary17': 'SW', 'Boundary18': 'SDY',
                              'Boundary19': 'SW', 'Boundary20': 'SW', 'Boundary21': 'SW'},
            'Direction': 1,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '双实线实实实实六车道'}
dict24_1 = {'Start': (0, 0),
            'LW': (20, 3.5),
            'DX': (10, 5),
            'LaneNumber': 18,
            'BoundaryNumber': 21,
            'LaneAssetType': {'Boundary1': 'SW', 'Boundary2': 'DW', 'Boundary3': 'DW', 'Boundary4': 'SDY',
                              'Boundary5': 'SW', 'Boundary6': 'SW', 'Boundary7': 'SW',
                              'Boundary8': 'SW', 'Boundary9': 'DW', 'Boundary10': 'DW', 'Boundary11': 'SDY',
                              'Boundary12': 'SW', 'Boundary13': 'SW', 'Boundary14': 'SW',
                              'Boundary15': 'SW', 'Boundary16': 'DW', 'Boundary17': 'DW', 'Boundary18': 'SDY',
                              'Boundary19': 'SW', 'Boundary20': 'SW', 'Boundary21': 'SW'},
            'Direction': 1,
            'Function': '+',
            'K': '-0',
            'Type': 'ulane',
            'Flag': '双实线虚虚实实六车道'}